export enum SubCategory {
    WeightManagement = 'WeightManagement',
    Performance = 'Performance',
    Protein = 'Protein',
    WomensClothes = 'WomensClothes',
    WomensAccessories = 'WomensAccessories',
    MensClothes = 'MensClothes',
    MensAccessories = 'MensAccessories',
    WomensSportShose = 'WomensSportShose',
    MensSportShose = 'MensSportShose',
    VitaminsAndHealth = 'VitaminsAndHealth',
}
export enum SubSubCategory {
    ProteinWeightGainers = 'ProteinWeightGainers',
    ProteinPlantProtein = 'ProteinPlantProtein',

    FishOil = 'FishOil',
    Multivitamins = 'Multivitamins',
    LCarnitine = 'LCarnitine',
    FatBurners = 'FatBurners',
    PostWorkoutRecovery = 'PostWorkoutRecovery',
    PreWorkout = 'PreWorkout',
    CaseinProtein = 'CaseinProtein',
    WheyProtein = 'WheyProtein',
    WomensClothesPantsAndLeggings = 'WomensClothesPantsAndLeggings',
    WomensClothesCropTops = 'WomensClothesCropTops',
    WomensClothesHoodiesAndJackets = 'WomensClothesHoodiesAndJackets',
    WomensClothesShorts = 'WomensClothesShorts',
    WomensClothesSportsBras = 'WomensClothesSportsBras',
    WomensClothesSwimwear = 'WomensClothesSwimwear',
    WomensClothesTShirtsAndTops = 'WomensClothesTShirtsAndTops',
    WomensClothesSleevelessandTankTops = 'WomensClothesSleevelessandTankTops',
    WomensClothesUnderwearAndSocks = 'WomensClothesUnderwearAndSocks',
    WomensAccessoriesSunglassesAndEyewearAccessories = 'WomensAccessoriesSunglassesAndEyewearAccessories',
    WomensAccessoriesScarvesAndWraps = 'WomensAccessoriesScarvesAndWraps',
    WomensAccessoriesGlovesAndMittens = 'WomensAccessoriesGlovesAndMittens',
    WomensAccessoriesHatsAndCaps = 'WomensAccessoriesHatsAndCaps',
    WomensAccessoriesEarmuffs = 'WomensAccessoriesEarmuffs',
    WomensAccessoriesHandbagAccessories = 'WomensAccessoriesHandbagAccessories',
    WomensAccessoriesKeyringsAndKeychains = 'WomensAccessoriesKeyringsAndKeychains',
    WomensAccessoriesWalletsAndCardCases = 'WomensAccessoriesWalletsAndCardCases',
    MensClothesBaselayers = 'MensClothesBaselayers',
    MensClothesHoodiesAndJackets = 'MensClothesHoodiesAndJackets',
    MensClothesShorts = 'MensClothesShorts',
    MensClothesPants = 'MensClothesPants',
    MensClothesStringers = 'MensClothesStringers',
    MensClothesTShirtsAndTops = 'MensClothesTShirtsAndTops',
    MensClothesSleevelessandTankTops = 'MensClothesSleevelessandTankTops',
    MensClothesUnderwearAndSocks = 'MensClothesUnderwearAndSocks',
    MensAccessoriesBelts = 'MensAccessoriesBelts',
    MensAccessoriesSunglassesAndEyewearAccessories = 'MensAccessoriesSunglassesAndEyewearAccessories',
    MensAccessoriesScarvesAndWraps = 'MensAccessoriesScarvesAndWraps',
    MensAccessoriesGlovesAndMittens = 'MensAccessoriesGlovesAndMittens',
    MensAccessoriesHatsAndCaps = 'MensAccessoriesHatsAndCaps',
    MensAccessoriesEarmuffs = 'MensAccessoriesEarmuffs',
    MensAccessoriesHandbagAccessories = 'MensAccessoriesHandbagAccessories',
    MensAccessoriesKeyringsAndKeychains = 'MensAccessoriesKeyringsAndKeychains',
    MensAccessoriesWalletsAndCardCases = 'MensAccessoriesWalletsAndCardCases',
    MensAccessoriesSuspenders = 'MensAccessoriesSuspenders',
}

export enum Category {
    Supplements = 'Supplements',
    Mens = 'Mens',

    WorkoutPlan = 'WorkoutPlan',
    Blogs = 'Blogs',
    OurCommunity = 'OurCommunity',

    Sarms = 'Sarms',
    HomePage = 'HomePage',
    Account = 'Account',

    Womens = 'Womens',
}
