export enum Paths {
    BackendBase = '/api/v1',
    AdminProducts = '/admin/page/products',
    AdminHomePage = '/admin/page',
    AdminFishOil = '/admin/page/supplements/vitamins-and-health/fish-oil',
    AdminMultivitamins = '/admin/page/supplements/vitamins-and-health/multivitamins',
    AdminLCarnitine = '/admin/page/supplements/weight-management/l-carnitine',
    AdminFatBurners = '/admin/page/supplements/weight-management/fat-burners',
    AdminPostWorkoutRecovery = '/admin/page/supplements/performance/post-workout-recovery',
    AdminPreWorkout = '/admin/page/supplements/performance/pre-workout',
    AdminCaseinProtein = '/admin/page/supplements/protein/casein-protein',
    AdminWheyProtein = '/admin/page/supplements/protein/whey-protein',
    AdminVitaminsAndHealth = '/admin/page/supplements/vitamins-and-health',
    AdminWeightManagement = '/admin/page/supplements/weight-management',
    AdminPerformance = '/admin/page/supplements/performance',
    AdminProtein = '/admin/page/supplements/protein',
    AdminAccountsManagement = '/admin/page/admin-accounts-management',
    AdminContacts = '/admin/page/contacts',
    AdminSupplements = '/admin/page/supplements',
    AdminSarms = '/admin/page/sarms',
    AdminFashion = '/admin/page/fashion',
    AdminWorkoutPlan = '/admin/page/workout-plan',
    AdminBlogs = '/admin/page/blogs',
    AdminOurCommunity = '/admin/page/our-community',
    AdminAddNewProduct = '/admin/page/add-new-product',
}
